- .github/README.md
- module/extensions/default.nix
- module/firefox/userChrome.nix
- module/hm.nix
> feat: make nixpak optional feature

- .github/FUNDING.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/labels.yml
- .github/workflows/pr-labels.yml
adds a PR template as well as CI-managed labels for PRs and issues
> CI: housecleaning

- .github/README.md
> Update readme with new option

- .github/README.md
- module/hm.nix
The module will error if imported.
It will not error if imported.
-
-
-
> fix: incorrect builtin usage in examples

- .github/FUNDING.yml
> feat: liberapay

- modules/hm/default.nix
> feat: schizofox .desktop entry

- modules/hm/default.nix
> fix: path issue

- modules/hm/default.nix
See #24 
Fixes #24 
skill issue
also ugly diff because alejandra :(
> Theme null checks

- .gitignore
- flake.lock
- flake.nix
- tests/basic.nix
- tests/default.nix
- tests/profiles/test-setup.nix
No tests
- Yes tests
- Convenient access to a basic interactive VM test to quickly view changes in a stock environment (`nix run .#test`)
Draft because there aren't any actual tests yet, just the initial structure for them. TODO: Come up with features to test.
Dependencies:
- #27
> NixOS tests

- .github/README.md
Typos exist in the readme.
The typos that I noticed no longer exist in the readme.
> docs: fix typos in README

- modules/hm/firefox/default.nix
- modules/hm/firefox/preferences.nix
> firefox: preferences cannot be a function

- modules/hm/default.nix
- modules/hm/firefox/default.nix
- modules/hm/firefox/extensions/default.nix
@Gerg-L ily but please take your meds
> modules/hm: hopefully fix all gerg skill issues

- modules/hm/firefox/default.nix
Adds a few extra security policies.
> schizofox: more security-related policies

- default.nix
> un-stupid flake-compat

- .github/labels.yml
- .github/workflows/check.yml
- .github/workflows/labels.yml
- .github/workflows/pr-labels.yml
- modules/hm/firefox/userContent.nix
- modules/hm/options/security.nix
> firefox/userContent: fix invalid extraContentCss reference

- .github/README.md
> docs(readme): add import statement to configuration

- modules/hm/options/theme.nix
> chore: update doc strings

- .github/README.md
- modules/hm/firefox/extensions/default.nix
- modules/hm/firefox/userChrome.nix
- modules/hm/options/extensions.nix
- modules/hm/options/renamed.nix
- modules/hm/options/theme.nix
> refactor: restructure some options

- modules/hm/firefox/preferences/default.nix
> fix: drmFix option

- modules/hm/firefox/preferences/default.nix
> feat: disable session restore

- .github/workflows/update.yml
- flake.lock
Adds a basic CI to update flake inputs every week. Updates flake inputs manually.
> flake: bump inputs

- modules/hm/firefox/default.nix
- modules/hm/firefox/preferences/default.nix
- modules/hm/options/misc.nix
- modules/hm/options/security.nix
- Add option to enable captive portals
- Add option to show bookmarks in toolbar
> Feat: add options to show bookmarks in toolbar on startup and enable captive portals

- modules/hm/firefox/userChrome.nix
- modules/hm/firefox/userContent.nix
- modules/hm/options/theme.nix
- pkgs/simplefox/userChrome.nix
> feat: add a lot of color overrides

- .github/workflows/update.yml
- flake.lock
Fix the flake update CI, bumps flake inputs.
> CI: checkout with repo secret

- .gitignore
.direnv isn't ignored by git
- .direnv is ignored by git
-
-
Sorry to make such a minor PR.
I forked and cloned to see if I can implement some feature I want, then run `direnv allow`, to see `.direnv` wasn't on gitignore
> feat: add .direnv to gitignore

- modules/home-manager/firefox/default.nix
- modules/home-manager/options/misc.nix
ff sync is hard disabled
u can toggle it on
not sure if this enables just sync or enables 9999999999999 backdoors but its fine for me
> feat: add option to enable firefox sync

- .github/README.md
- modules/home-manager/firefox/preferences/default.nix
- modules/home-manager/options/misc.nix
- `contextMenu.enable` is now an option in the misc configuration
> feat: add contextMenu option

- modules/home-manager/options/misc.nix
Fixes the formatting issue introduced in #106
> options/misc: format via alejandra

- flake/modules/home-manager/options/security.nix
Issue Number: #125
- User agent changed to `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0`
I believe some sites might expire sessions because of it or change which assets/image formats are used
> options/security: update user-agent to Firefox/128.0

- flake/modules/common/firefox/default.nix
- flake/modules/home-manager/default.nix
#129 introduced couple issues into the HM module: lib.optionals caused the home manager module build to fail and user.js was written with wrong contents. This fixes those two issues.
-
-
-
> Fix home manager module issues from #129
